name: release

on:
  release:
    types:
      - created

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - run: |
        npm ci
        npm install -g expo-cli

    - name: Test
      run: npm test

    - name: Build
      run: npm run build

    - name: List output files
      run: ls

    - name: gn deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ftp://ftp.garethnunns.com/
        ftp-username: e2@garethnunns.com
        ftp-password: ${{ secrets.gn_ftp_password }}
        local-dir: web-build
