name: Release

on:
  release:
    types:
      - created

env:
  NODE_VERSION: '12.x'

jobs:
  web:
    name: Web Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install
      run: |
        yarn install --frozen-lockfile
        yarn global add expo-cli

    - name: Test
      run: yarn test

    - name: Build
      run: yarn run build-web

    - name: gn deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ftp://ftp.garethnunns.com/
        ftp-username: e2@garethnunns.com
        ftp-password: ${{ secrets.gn_ftp_password }}
        local-dir: web-build
  
  desktop:
    name: Desktop Release

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: yarn install
        run: |
          yarn install

      - name: Linux/Mac Build & Copy to artifacts
        if: matrix.os != 'windows-latest'
        run: |
          GH_TOKEN=${{secrets.GITHUB_TOKEN}} yarn run build-desktop
          mkdir artifacts
          mv dist/*.zip dist/*.AppImage artifacts || true

      - name: Windows Build & Copy to artifacts
        if: matrix.os == 'windows-latest'
        run: |
          yarn run build-desktop
          mkdir artifacts
          mv dist/*.exe artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: artifacts
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}